server:
  port: 9257
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh     #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   # ************动态路由****************
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由
#            - After=2021-07-23T17:29:25.585+08:00[Asia/Shanghai]   #ZonedDateTime now = ZonedDateTime.now();
#            - Before
#            - Between
#            - Cookie=username,mdxdd    #curl http://localhost:9257/payment/get/1 --cookie "username=mdxdd"
#            - Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式  curl http://localhost:9257/payment/get/1 -H "X-Request-Id:123"
#            - Host=**.atguigu.com #curl http://localhost:9257/payment/get/1 -H "Host:www.atguigu.com"
#            - Method=GET,POST
#            - Path=/red/{segment},/blue/{segment}   #Map<String, String> uriVariables = ServerWebExchangeUtils.getPathPredicateVariables(exchange);
                                                    #String segment = uriVariables.get("segment");
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: cloud-gateway-service
